name: gha-result
on:
  push:
    branches:
      - branch-1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.0
      - name: Set up cache
        uses: actions/cache@v3.3.1
        with:
            path: "${{ github.workspace }}/.m2/repository"
            key: "${{ runner.os }}-path"
      - uses: actions/setup-java@v3.12.0
        with:
          distribution: zulu
          java-version: '8'

      - name: My Custom Maven Build Step
        run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

      - name: Sending email notification when build fails
        if: always() && failure()
        run: echo "Error occured,Build failed!" | mail -s "Build failed on branch develop" a@binarywang.com
