name: My Custom Workflow for Manual Migration

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: '8'
            architecture: 'x64'
            distribution: 'adopt'

      - name: My Custom Maven Build Step
        run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

      - name: Caching the Maven dependencies manually
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-

      - name: Sending email notification when build fails
        if: always() && failure()
        run: echo "Error occured,Build failed!" | mail -s "Build failed on branch develop" a@binarywang.com
