name: gha2-results

on:
  push:
    branches:
      - branch-2
  pull_request:
    branches:
      - branch-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Caching the Maven dependencies manually
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: My Custom Maven Build Step
        run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

      - name: Sending email notification when build fails
        if: always() && failure()
        run: echo "Error occured,Build failed!" | mail -s "Build failed on branch branch-2" a@binarywang.com
