name: My Custom Workflow for Manual Migration

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: '8'
            architecture: 'x64'
            distribution: 'adopt'

      - name: My Custom Maven Build Step
        run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true
