name: My Custom Workflow for Manual Migration

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setting up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: '8'
