name: gha2-results

on:
  push:
    branches:
      - branch-2
  pull_request:
    branches:
      - branch-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@version

      - name: Caching the Maven dependencies manually
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }
          uses: actions/setup-java@version
          with:
            java-version: ${{ matrix.java }}

      run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

macos:
  jdk: openjdk8

