name: gha2-results

on:
  push:
    branches:
      - branch-2
  pull_request:
    branches:
      - branch-2

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Caching the Maven dependencies
          uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashfiles(arg) }}
        uses: actions/cache@version
        - name: build with maven-
          uses: actions/setup-java@version
          with:
            java-version: ${{ matrix.java }}
          uses: actions/checkout@version
      run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true

macos:
  jdk: openjdk8

